blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name= "blog"

urlpatterns = [
    path('postComment', views.postComment, name="postComment"),
    path('', views.blogHome, name="bloghome"),
    path('<str:slug>', views.blogPost, name="blogPost"),
    path('start/', views.start, name="start"),
]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views


app_name= "home"

urlpatterns = [
    path('', views.home, name="home"),
   
    
    path('search', views.search, name="search"),
    path('signup', views.handleSignUp, name="handleSignUp"),
    path('login', views.handeLogin, name="handleLogin"),
    path('logout', views.handelLogout, name="handleLogout"),
    path('details/<int:id>/', views.detail, name="detail"),
    path('create/', views.create, name="create"),
    path('edit/<int:id>/', views.edit, name="edit"),
    path('delete/<int:id>/', views.delete, name="delete"),
    path('addrating/<int:id>/', views.add_rating, name="add_rating"),
    path('editrating/<int:car_id>/<int:review_id>/', views.editRating, name="edit_rating"),
    path('deleterating/<int:car_id>/<int:review_id>/', views.deleteRating, name="delete_rating"),
   
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Car(models.Model):
    # fields for the car table
    name = models.CharField(max_length=300)
    model = models.IntegerField()
    horsepower = models.IntegerField()
    description = models.TextField(max_length=5000)
    price = models.IntegerField(default=0)
    
    averageRating = models.FloatField(default=0)
    image = models.URLField(default=None, null=True)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

class Rating(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=5000)
    rating = models.FloatField(default=0)

    def __str__(self):
        return self.user.username

home/forms.py
from django import forms
from .models import *

# car add form
class CarForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = ('name', 'model', 'horsepower', 'description', 'price', 'image')

class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ("comment", "rating")

home/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import Car
from django.contrib import messages 
from django.contrib.auth.models import User 
from django.contrib.auth  import authenticate,  login, logout
from blog.models import Post
from math import ceil
from django.db.models import Avg
from .forms import *

def home(request):
    
    cars = Car.objects.all()
    n= len(cars)
    nSlides= n//4 + ceil((n/4) + (n//4))
    params={'no_of_slides':nSlides, 'range':range(1,nSlides), 'car': cars}
    return render(request,"home/home.html", params)
    

def detail(request, id):
    car = Car.objects.get(id=id) # select * from car where id=id
    reviews = Rating.objects.filter(car=id).order_by("-comment")

    average = reviews.aggregate(Avg("rating"))["rating__avg"]
    if average == None:
        average = 0
    average = round(average, 2)
    context = {
        "car": car,
        "reviews": reviews,
        "average": average
    }
    return render(request, 'home/details.html', context)
   

    



def search(request):
    query=request.GET['query']
    if len(query)>78:
        allPosts=Post.objects.none()
    else:
        allPostsTitle= Post.objects.filter(title__icontains=query)
        allPostsAuthor= Post.objects.filter(author__icontains=query)
        allPostsContent =Post.objects.filter(content__icontains=query)
        allPosts=  allPostsTitle.union(allPostsContent, allPostsAuthor)
    if allPosts.count()==0:
        messages.warning(request, "No search results found. Please refine your query.")
    params={'allPosts': allPosts, 'query': query}
    return render(request, 'home/search.html', params)

def handleSignUp(request):
    if request.method=="POST":
        # Get the post parameters
        username=request.POST['username']
        email=request.POST['email']
        fname=request.POST['fname']
        lname=request.POST['lname']
        pass1=request.POST['pass1']
        pass2=request.POST['pass2']

        # check for errorneous input
        if len(username)>10:
            messages.error(request, " Your user name must be under 10 characters")
            return redirect('home:home')

        if not username.isalnum():
            messages.error(request, " User name should only contain letters and numbers")
            return redirect('home:home')
        if (pass1!= pass2):
             messages.error(request, " Passwords do not match")
             return redirect('home:home')
        
        # Create the user
        myuser = User.objects.create_user(username, email, pass1)
        myuser.first_name= fname
        myuser.last_name= lname
        myuser.save()
        messages.success(request, " Your Account has been successfully created! Click on Login now")
        return redirect('home:home')

    else:
        return HttpResponse("404 - Not found")



def handeLogin(request):
    if request.method=="POST":
        # Get the post parameters
        loginusername=request.POST['loginusername']
        loginpassword=request.POST['loginpassword']

        user=authenticate(username= loginusername, password= loginpassword)
        if user is not None:
            login(request, user)
            messages.success(request, "Successfully Logged In")
            return redirect("home:home")
        else:
            messages.error(request, "Invalid credentials! Please try again")
            return redirect("home:home")

    return HttpResponse("<h3>Create your Account using Signup</h3>")
   

    

def handelLogout(request):
    logout(request)
    messages.success(request, "Successfully logged out")
    return redirect('home:home')




def create(request):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            if request.method == "POST":
                form = CarForm(request.POST or None)

                
                if form.is_valid():
                    data = form.save(commit=False)
                    data.save()
                    return redirect("home:home")
            else:
                form = CarForm()
            return render(request, 'home/create.html', {"form": form, "controller": "Add Car"})
        
        
        else:
            return redirect("home:home")

    
    return redirect("home:handleLogin")   

def edit(request, id):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            # get the car linked with id
            car = Car.objects.get(id=id)

            # form check
            if request.method == "POST":
                form = CarForm(request.POST or None, instance=car)
                # check if form is valid
                if form.is_valid():
                    data = form.save(commit=False)
                    data.save()
                    return redirect("home:detail", id)
            else:
                form = CarForm(instance=car)
            return render(request, 'home/create.html', {"form": form, "controller": "Edit"})
        # if they are not admin
        else:
            return redirect("home:home")

    # if they are not loggedin
    return redirect("home:handleLogin") 

def delete(request, id):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            # get the car
            car = Car.objects.get(id=id)

            # delete the car
            car.delete()
            return redirect("home:home")
        # if they are not admin
        else:
            return redirect("home:home")

    # if they are not loggedin
    return redirect("home:handleLogin") 


def add_rating(request, id):
    if request.user.is_authenticated:
        car = Car.objects.get(id=id)
        if request.method == "POST":
            form = RatingForm(request.POST or None)
            if form.is_valid():
                data = form.save(commit=False)
                data.comment = request.POST["comment"]
                data.rating = request.POST["rating"]
                data.user = request.user
                data.car = car
                data.save()
                return redirect("home:detail", id)
        else:
            form = RatingForm()
        return render(request, 'home/details.html', {"form": form})
    else:
        return redirect("home:handleLogin")

def editRating(request, car_id, review_id):
    if request.user.is_authenticated:
        car = Car.objects.get(id=car_id)
        # review
        review = Rating.objects.get(car=car, id=review_id)

        # check if the review was done by the logged in user
        if request.user == review.user:
            # grant permission
            if request.method == "POST":
                form = RatingForm(request.POST, instance=review)
                if form.is_valid():
                    data = form.save(commit=False)
                    if (data.rating > 10) or (data.rating < 0):
                         error = "Out or range. Please select rating from 0 to 10."
                         return render(request, 'home/editrating.html', {"error": error, "form": form})
                    else:
                        data.save()
                        return redirect("home:detail", car_id)
            else:
                form = RatingForm(instance=review)
            return render(request, 'home/editrating.html', {"form": form})
        else:
            return redirect("home:detail", car_id)
    else:
        return redirect("home:handleLogin")


# delete reivew
def deleteRating(request, car_id, review_id):
    if request.user.is_authenticated:
        car = Car.objects.get(id=car_id)
        # review
        review = Rating.objects.get(car=car, id=review_id)

        # check if the review was done by the logged in user
        if request.user == review.user:
            # grant permission to delete
            review.delete()

        return redirect("home:detail", car_id)
            
    else:
        return redirect("home:handleLogin")

templates/home/create.html
{% extends 'base.html' %}
{% block createactive %} active {% endblock createactive %}

{% load crispy_forms_tags %}


{% block body %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">{{ controller }}</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                <input type="submit" value="{{ controller }}" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/home/details.html
{% extends 'base.html' %}


{% block body %}

<marquee><h1>I’d drive a million miles for one of your smiles.</h1></marquee>
<div class="container">
    <br>
    <div class="card">
        <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <img src="{{ car.image }}" alt="{{ car.name }}" class="img-fluid">
            </div>
            <div class="col-md-8">
                <h3 class="text-center">
                    {{ car.name }}
                </h3>
                <p>{{ car.description }}</p>
                <h5>Horspower: {{ car.horsepower }}</h5>
                <h5>Price: ${{ car.price }}</h5>
                <h5>Rating: {{ average }} out of 10</h5>
                {% if request.user.is_authenticated %}
                    {% if request.user.is_superuser %}
                <a href="{% url 'home:edit' car.id %}" class="btn btn-info">Edit</a>
                <a href="{% url 'home:delete' car.id %}" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this?');">Delete</a>
                     {% endif %}
                {% endif %}
               
            </div>
        </div>
    </div>
    </div>

    <div class="container">
        
            <h4> Review</h4>
            <form action="{% url 'home:add_rating' car.id %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="exampleFormControlTextarea1"><b>Write your review down below:</b></label>
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="comment" required></textarea>
                  </div>

                
                <input type="range" id="rangeInput" 
                    name="rating" min="0" max="10" value="0" step="0.5"
                    oninput="amount.value=rangeInput.value">                                                       
         
                <output name="amount" id="amount" for="rangeInput">0</output>
                
                <br>
                <div class="col-auto">
                    <button type="submit" class="btn btn-primary mb-2">Review</button>
                  </div>
            </form>
        </div>
    
    <br>
    <h3>Reviews:</h3>
    <div class="container">
        
            
            {% for review in reviews %}
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row no-gutters">
                  <div class="col-md-8">
                
                    <div class="card-body">
                        <h5 class="card-title">{{ review.user.username }}</h5>
                           
                               
                                <h5>{{ review.rating }}</h5>
                                {% if request.user == review.user %}
                                
                                <a href="{% url 'home:edit_rating' car.id review.id %}" class="btn btn-info">Edit</a>
                                <a href="{% url 'home:delete_rating' car.id review.id %}" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this?');">Delete</a>
                                {% endif %}

                            </div>
                            <div class="col-md-9">
                                <p class="card-text">{{review.comment}}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                {% endfor %}
        </div>
    </div>
</div>



{% endblock %}

templates/home/editrating.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}


{% block body %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Edit Review</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                {% if error %}
                    <strong style="color: red;">{{ error }}</strong>
                {% endif %}
                <input type="submit" value="Save Changes" class="btn btn-danger">
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/home/home.html
{% extends "base.html" %}
{% block homeactive %} active {% endblock homeactive %}

{% block body %}

<div class="container-fluid">
  <div class="row">
  
      <img class="pic" src="static/img/tesla1.png" class="img-fluid" alt="Responsive image">
      <img class="pic" src="static/img/wheel.jpg" class="img-fluid" alt="Responsive image">
      <img class="pic" src="static/img/wheels.jpg" class="img-fluid" alt="Responsive image">
      <img class="pic" src="static/img/bmw1.jpg" class="img-fluid" alt="Responsive image">
      <img class="pic" src="static/img/audi.jpg" class="img-fluid" alt="Responsive image">
      <img class="pic" src="static/img/j.jpg" class="img-fluid" alt="Responsive image">
      <img class="pic" src="static/img/honda1.jpg" class="img-fluid" alt="Responsive image">
  </div>
</div>
  <br>

  <div class="container">
    <h1>Below is the list of all the Rides</h1>
<div id="demo" class="carousel slide my-3" data-ride="carousel">
    <ul class="carousel-indicators">
      <li data-target="#demo" data-slide-to="0" class="active"></li>

       {% for i in range %}
      <li data-target="#demo" data-slide-to="{{i}}" ></li>
      {% endfor %}
    </ul>

    <!--Slideshow starts here -->
    <div class="container carousel-inner no-padding">

      <div class="carousel-item active">
       


        {% for i in car %}
        <div class="col-xs-3 col-sm-3 col-md-3">
          <div class="card" style="width: 18rem;">
            <img src='{{i.image}}' class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">{{i.name}}</h5>
              <p class="card-text"><strong>Model: </strong>{{i.model}}</p>
              <p class="card-text"><strong>HorsePower: </strong>{{i.horsepower}}</p>
              <p class="card-text"><strong>Price: </strong>${{i.price}}</p>            
              
              <p class="card-text">{{i.description}}</p>
              <a href="/details/{{i.id}}"  class="btn btn-primary">Read More</a>
            </div>
          </div>
        </div>
        {% if forloop.counter|divisibleby:4 and forloop.counter > 0 and not forloop.last %}
      </div><div class="carousel-item">
        {% endif %}

        {% endfor %}
    </div>



</div>
</div>
    <!-- left and right controls for the slide -->
    <a class="carousel-control-prev " href="#demo" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true" ></span>
       <span class="sr-only">Previous</span>
     </a>
     <a class="carousel-control-next" href="#demo" role="button" data-slide="next">
       <span class="carousel-control-next-icon" aria-hidden="true"></span>
       <span class="sr-only">Next</span>
     </a>
      
       </div>

  
   

	{% endblock %}

templates/home/search.html
{% extends 'base.html' %}

{% block title %} Search Results {% endblock title %}
{% block blogactive %} active {% endblock blogactive %} 


{% block body %}
<div class="container my-3">
    <h2>Search results : </h2>
    {% if allPosts|length < 1 %}
   <p>No search results</p>
    Your search query : <b>{{query}}</b> did not match any documents. <br>
    Suggestions:
    <ul>
    <li>Make sure that all words are spelled correctly.</li>
    <li>Try more general keywords.</li>
   <li> Try fewer keywords.</li>
   <li> Try different keywords.</li>
    </li>
    </ul>


    {% endif %}
    {% for post in allPosts  %}
    <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 my-4 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
            <strong class="d-inline-block mb-2 text-primary">Article  by {{post.author}}</strong>
            <h3 class="mb-0">{{post.title}}</h3>
            <div class="mb-1 text-muted">{{post.datetime}}</div>
            <p class="card-text mb-auto">{{post.content| truncatechars:500}}</p>
            <div class="my-2">
            	<a href="/blog/{{post.slug}}" role="button" class="btn btn-primary">Continue reading</a>
            </div>
            
        </div>
        
        </div>

        {% endfor %}
    </div>
 {% endblock %}