blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name= "blog"

urlpatterns = [
    path('postComment', views.postComment, name="postComment"),
    path('', views.blogHome, name="bloghome"),
    path('<str:slug>', views.blogPost, name="blogPost"),
    path('start/', views.start, name="start"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/style.css">
    

    <title>{% block title %}   {% endblock title %}</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Hitting the Wheels</a>
        {% if user.is_authenticated %}
        <button class="navbar-toggler" type="button" data-toggle  ="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item {% block homeactive %}  {% endblock homeactive %}">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            
            <li class="nav-item {% block createactive %}  {% endblock createactive %}" >
              <a class="nav-link" href="/create">Create</a>
            </li>
           
            <li class="nav-item {% block blogactive %}  {% endblock blogactive %} ">
              <a class="nav-link" href="/blog">Discussion</a>
            </li>
            <li class="nav-item {% block discussionactive %}  {% endblock discussionactive %} ">
              <a class="nav-link" href="{% url 'blog:start' %}" >Start your own Discussion</a>
            </li>
            
          </ul>
          <div class="ml-auto form-inline ">
          <form method="get" action="/search"class="my-2 my-lg-0 mx-3">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="query" id="query">
            <button class="btn btn-primary my-2 my-sm-0 " type="submit">Search</button>
            
          </form>

     


<ul class="navbar-nav mr-2">
<li class="nav-item dropdown">
<a class="nav-link dropdown-toggle" href='#' id="navbarDropdown" role="button" data-toggle="dropdown"> Welcome {{request.user}}</a>
<div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/logout">Logout</a>

        </div>
      </li>
      </ul>
      </div>
{% else %}
  <!-- Button to  trigger Login modal -->
<button type="button" class="btn btn-primary mr-2" data-toggle="modal" data-target="#loginModal">
Login
</button>

<button type="button" class="btn btn-primary mr-2" data-toggle="modal" data-target="#signupModal">
SignUp
</button>
{% endif %}


        </div>
      </nav>
      {% for message in messages  %}            
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <strong>Message : </strong> {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
      {% endfor %}    



 

<!-- SignUp Modal -->
<div class="modal fade" id="signupModal" tabindex="-1" aria-labelledby="signupModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="signupModalTitle">SignUp Here</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action= "/signup" method='post'>
  <div class="form-group">
    <label for="username">Username</label>
    <input type="text" class="form-control" id="username" name="username" placeholder="Choose a unique username" required>
  </div>
  <div class="form-group">
    <label for="fname">First Name</label>
    <input type="text" class="form-control" id="fname" name="fname" placeholder="Enter Your First Name" required>
  </div>
  <div class="form-group">
    <label for="lname">Last Name</label>
    <input type="text" class="form-control" id="lname" name="lname" placeholder="Enter Your Last Name" required>
  </div>
  <div class="form-group">
    <label for="email">Email address</label>
    <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com" required>
  </div>
  <div class="form-group">
    <label for="pass1">Choose a password</label>
    <input type="password" class="form-control" id="pass1" name="pass1" placeholder="Choose Your Password" required>
  </div>
  <div class="form-group">
    <label for="pass2">Confirm Password</label>
    <input type="password" class="form-control" id="pass2" name="pass2" placeholder="Enter your password again" required>
  </div>
 

        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Submit</button>
</form>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>


      {% block body %}  {% endblock body %}
      {% block js %}
      {% endblock js %}

<!-- Login Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="loginModalTitle">Login Here</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="/login" method="POST"> {% csrf_token %}
  <div class="form-group">
    <label for="username">Username</label>
    <input type="text" class="form-control" id="loginusername" name="loginusername" placeholder="Enter your username "required>
  </div>
  <div class="form-group">
    <label for="pass">Enter your password </label>
    <input type="password" class="form-control" id="loginpassword" name="loginpassword" placeholder="Enter your password "required>
  </div>
 
        <button type="submit" class="btn btn-primary">Submit</button>
</form>
      </div>
       <div class="modal-footer">
      </div>

    <!-- Optional JavaScript -->
    <script src="static/main.js"></script>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    
  </body>
 
</html>